[tool.poetry]
name = "virtual-hedge-fund"
version = "0.1.0"
description = ""
authors = ["Timenikhil <48746822+Timenikhil@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
fastapi = {extras = ["standard"], version = "^0.120.1"}
requests = "^2.32.5"
python-logging-loki = "^0.3.1"
prometheus-fastapi-instrumentator = "^7.1.0"
opentelemetry-instrumentation-fastapi = "^0.59b0"
opentelemetry-exporter-otlp = "^1.38.0"
libsql-client = "^0.3.1"
libsql = "^0.1.11"
pandas = "^3.0.2"
scipy = "^1.17.1"
scipy-stubs = "~=1.17.1"
firebase-admin = "^7.4.0"
scikit-learn = "^1.8.0"
pmdarima = "^2.1.1"
neo-ls-svm = "^0.3.0"



[tool.poetry.group.dev.dependencies]
poethepoet = "^0.27.0"

[tool.poe.tasks]
up-qr = "docker compose -f docker-compose.quantrocket.yml up -d"
up-api = "docker compose -f docker-compose.vhf.yml up --build"
up-all = "docker compose -f docker-compose.quantrocket.yml -f docker-compose.vhf.yml up --build"
down = "docker compose -f docker-compose.quantrocket.yml -f docker-compose.vhf.yml down"
ps = "docker compose -f docker-compose.quantrocket.yml -f docker-compose.vhf.yml ps"
logs-api = "docker compose -f docker-compose.vhf.yml logs -f vhf-api"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
